connector.allowed.credentials: very-secure:password

server:
  use-forward-headers: true
  tomcat:
    remote_ip_header: x-forwarded-for

endpoints:
  enabled: false
  info:
    enabled: true
    sensitive: false
  health:
      enabled: true
      sensitive: false
      time-to-live: 5000

info:
  build:
    name: @project.name@
    description: @project.description@
    version: @project.version@
